name: mavenapp

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2
     - name: build the app
       run: mvn package 
     - name: tomcat deploy
       run: curl -v -u admin:admin  -T /home/ec2-user/actions-runner/_work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.1-SNAPSHOT.war 'http://ec2-3-109-121-88.ap-south-1.compute.amazonaws.com:8080/manager/text/deploy?path=/jmsth39spring3&update=true'
